#!/usr/bin/env bash
set -eou pipefail

# List audio devices
audio_devices="$(
wpctl status | 
awk '/Sinks:/ {start=1} /Sources:/ {start=0} start' | 
rg '[0-9]' | 
awk '{for(i=2; i<=NF; i++) printf $i (i<NF?OFS:ORS)}' | 
sed 's/*/ /'|
sed 's/^  //')"
chosen=0
while [ $chosen -le 0 ] 
do 
    echo "Audio devices: "
    echo " "
    echo "$audio_devices"| awk  '{print $2" "$3" "$4}'|  nl -w2 -s') ' 
    read -p "Choose one: " chosen
done 
wpctl set-default $(echo "$audio_devices" | awk '{print}' |  nl -w2 -s ') '| sed -n "$chosen"p | awk '{print $2}' | sed 's/\.//')



