#!/usr/bin/env bash

device=$1

case "$device" in
    headset)pactl set-default-sink alsa_output.usb-Corsair_Corsair_HS65_SURROUND-00.analog-stereo
    ;;
    box)pactl set-default-sink alsa_output.pci-0000_2c_00.4.analog-stereo 
    ;;
    hdmi)pactl set-default-sink alsa_output.pci-0000_08_00.1.hdmi-stereo 
    ;;
    *) echo "Could'nt find the device" 
    ;;
esac

