#!/usr/bin/env bash

# @fomatter: on
set -eou pipefail

choice=$(gum choose $(
        wpctl status |
        awk '/Sinks:/ {start=1} /Sources:/ {start=0} start' |
        rg '[0-9]' |
        awk '{for(i=2; i<=NF; i++) printf $i (i<NF?OFS:ORS)}' |
        sed 's/*/ /'|
        sed 's/^  //'|
        awk '{print $2}'
))


wpctl set-default $(wpctl status \
        | awk '/Sinks:/ {start=1} /Sources:/ {start=0} start' \
        | rg '[0-9]' \
        | awk '{for(i=2; i<=NF; i++) printf $i (i<NF?OFS:ORS)}' \
        | sed 's/*/ /' \
        | sed 's/^  //' \
        | rg "$choice" \
        | awk '{print $1}' \
        | sed 's/\.//' \
    )

